In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'Understand the meaning of word',
    'your videos are good'

]
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'Understand the meaning of word',
 'your videos are good']

In [3]:
# Define the voab size
voc_size= 10000

In [4]:
## One hot representation
one_hot_repr=[one_hot(words, voc_size) for words in sent]
one_hot_repr

[[2196, 6702, 6517, 844],
 [2196, 6702, 6517, 4075],
 [2196, 1776, 6517, 3045],
 [9689, 2235, 5684, 924, 3327],
 [9689, 2235, 5684, 924, 1646],
 [7731, 2196, 4271, 6517, 495],
 [2677, 8768, 9180, 924]]

In [8]:
## Word embedding representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2196 6702 6517  844]
 [   0    0    0    0 2196 6702 6517 4075]
 [   0    0    0    0 2196 1776 6517 3045]
 [   0    0    0 9689 2235 5684  924 3327]
 [   0    0    0 9689 2235 5684  924 1646]
 [   0    0    0 7731 2196 4271 6517  495]
 [   0    0    0    0 2677 8768 9180  924]]


In [10]:
## Feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 454ms/step


array([[[ 0.0002043 ,  0.03308446, -0.02773583, -0.03259857,
          0.03664216, -0.00132968,  0.04830157,  0.03743691,
          0.04570985,  0.03874182],
        [ 0.0002043 ,  0.03308446, -0.02773583, -0.03259857,
          0.03664216, -0.00132968,  0.04830157,  0.03743691,
          0.04570985,  0.03874182],
        [ 0.0002043 ,  0.03308446, -0.02773583, -0.03259857,
          0.03664216, -0.00132968,  0.04830157,  0.03743691,
          0.04570985,  0.03874182],
        [ 0.0002043 ,  0.03308446, -0.02773583, -0.03259857,
          0.03664216, -0.00132968,  0.04830157,  0.03743691,
          0.04570985,  0.03874182],
        [-0.02343001, -0.02265075,  0.03738536, -0.0480491 ,
         -0.01456087,  0.00339859,  0.00519042, -0.01766937,
         -0.03337224,  0.03141204],
        [-0.04439164, -0.0341747 ,  0.0203359 , -0.00063431,
          0.03606   , -0.04792286,  0.03253937,  0.01027398,
          0.01848337, -0.01574171],
        [-0.03964534, -0.04283537,  0.0148845 ,  0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 2196, 6702, 6517,  844], dtype=int32)

In [16]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 306ms/step


array([[ 0.0002043 ,  0.03308446, -0.02773583, -0.03259857,  0.03664216,
        -0.00132968,  0.04830157,  0.03743691,  0.04570985,  0.03874182],
       [ 0.0002043 ,  0.03308446, -0.02773583, -0.03259857,  0.03664216,
        -0.00132968,  0.04830157,  0.03743691,  0.04570985,  0.03874182],
       [ 0.0002043 ,  0.03308446, -0.02773583, -0.03259857,  0.03664216,
        -0.00132968,  0.04830157,  0.03743691,  0.04570985,  0.03874182],
       [ 0.0002043 ,  0.03308446, -0.02773583, -0.03259857,  0.03664216,
        -0.00132968,  0.04830157,  0.03743691,  0.04570985,  0.03874182],
       [-0.02343001, -0.02265075,  0.03738536, -0.0480491 , -0.01456087,
         0.00339859,  0.00519042, -0.01766937, -0.03337224,  0.03141204],
       [-0.04439164, -0.0341747 ,  0.0203359 , -0.00063431,  0.03606   ,
        -0.04792286,  0.03253937,  0.01027398,  0.01848337, -0.01574171],
       [-0.03964534, -0.04283537,  0.0148845 ,  0.0439521 ,  0.0461139 ,
        -0.01400944,  0.04428748, -0.01434904